name: Build nanoOS with Buildroot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install All Required Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget cpio unzip rsync bc file sed make \
        binutils gcc g++ patch gzip bzip2 perl tar ccache git graphviz locales \
        libncurses5-dev libssl-dev cvs git mercurial subversion bash patch ncurses-dev

    - name: Clone Buildroot Source
      run: |
        # Menggunakan git clone langsung dari repositori resmi agar anti-gagal unduh
        git clone --depth 1 --branch 2024.02.x https://github.com

    - name: Configure Buildroot Default
      run: |
        cd buildroot
        make qemu_x86_64_defconfig

    - name: Compile OS Core
      run: |
        cd buildroot
        make FORCE_UNSAFE_CONFIGURE=1 -j$(nproc)

    - name: Upload OS Images Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nanoOS-images
        path: buildroot/output/images/
